# .rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "vendor/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: true
