# .rubocop.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "vendor/**/*"

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
